# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'DynamicBrushes' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PaletteKnife

    pod 'SwiftKVC', '~> 3.0.0'
    pod 'SwiftyJSON'
    pod 'AudioKit', '~> 4.1'
    
    pod 'Starscream'
    
    pod 'AWSCognito'
    pod 'AWSS3'
    pod 'AWSCore'
    
  target 'DynamicBrushesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DynamicBrushesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
